---
- hosts: all
  connection: local
  tasks:
    - ping:
    - ecl2_storage:
        cloud: devel
        state: present
        name: 'test-vs01-for-heat'
        subnet: 'ANSIBLE_SUBNET2'
        ip_addr_pool_start: '10.0.2.201'
        ip_addr_pool_end: '10.0.2.230'
        timeout: 600

    - ecl2_storage_volume:
        cloud: devel
        state: present
        iops_per_gb: 2
        name: 'test-ansible2'
        size: 100
        virtual_storage: 'test-vs01-for-heat'
        availability_zone: 'zone1-groupb'
        initiator_iqns:
          - 'iqn.1994-05.com.redhat:e887d78945e'
          - 'iqn.1994-05.com.redhat:5f9b99b9c43'
        timeout: 600

    - ecl2_storage_volume_stat:
        cloud: devel
        name: 'test-ansible2'

